import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Free Labubu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black w-[100vw] h-[100vh] text-white overflow-x-hidden">
      <body className={inter.className}>
        <div className="h-[100%]">
        <Navbar/>
        {children}
        </div>
        <div className="flex flex-col justify-center items-center py-[5%]">
          <div className="text-4xl">More</div>
          <div>

          </div>
        </div>
      </body>
    </html>
  );
}
//I ate 10 kids in mmyy  basement
//Free LABUBU//