import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Free Labubu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black w-[100vw] h-[100vh] text-white">
      <body className={inter.className}>
        <div>
        <Navbar/>
        {children}
        </div>
      </body>
    </html>
  );
}
//I ate 10 kids in mmyy  basement
//Free LABUBU//