import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/client";
import "./globals.css";
import Theme from "./theme"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Free Labubu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
//I ate 10 kids in mmyy  basement
//Free LABUBU//